version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db-attendance
      - redis-attendance
      - elasticsearch-attendance
    env_file:
      - .env
    networks:
      - backend

  db-attendance:
    container_name: db-attendance
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_AUTHENTICATION_PLUGIN: root
    ports:
      - "3322:3306"
    networks:
      - backend

  redis-attendance:
    container_name: redis-attendance
    image: redis:6.2.6
    restart: always
    ports:
      - "6380:6379"
    networks:
      - backend

  elasticsearch-attendance:
    container_name: elasticsearch-attendance
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    restart: always
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - backend

volumes:
  db-data:
  redis-data:
  es-data:

networks:
  backend: