version: '3.8'
services:
  app:
    build: .
    ports:
      - '5002:5002'
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: attendance
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ELASTICSEARCH_URL: http://elasticsearch:9200
      JWT_KEY: secret-key
    depends_on:
      - mysql
      - redis
      - elasticsearch
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - '3322:3306'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'