#!/bin/bash

echo "Rebuilding Docker containers..."

status2=$(docker images -f "dangling=true" -q | wc -l)
# Delete all none images
if [ $status2 -gt 0 ]; then
    echo "images not empty, removing them..."
    #docker rmi $(docker images -q)
    docker rmi $(docker images -f "dangling=true" -q)
    #docker network prune
    echo "done"
fi

#docker network create as_bridge;
/usr/local/bin/docker compose -f docker-compose.yml up --build -d
/usr/local/bin/docker compose -f docker-compose.yml ps