#!/bin/bash

# 1. Install Dependencies
echo "1. Installing node packages..."
npm install

# 2. Create .env
echo "2. Creating .env file..."
cat <<EOF > .env
# SERVER
PORT=3000

# DATABASE
DB_HOST=localhost
DB_USER=root
DB_PASSWORD=root
DB_NAME=attendance
DB_PORT=3322

# REDIS
REDIS_HOST=redis-attendance
REDIS_PORT=6379

# Elasticsearch
ELASTICSEARCH_HOST=http://elasticsearch-attendance:9200

# JWT
JWT_SECRET=mysecretkey
JWT_EXPIRES_IN=1d

# Email
SMTP_HOST=smtp.mailtrap.io
SMTP_PORT=2525
SMTP_USER=your_mailtrap_user
SMTP_PASS=your_mailtrap_password
EOF